#!/bin/bash
#PBS -A ERDCV00898ENQ
#PBS -l walltime=048:00:00
#PBS -l select=8:ncpus=24:mpiprocs=24
#PBS -q standard
#PBS -N bar
#PBS -j oe
#PBS -l application=proteus
#PBS -V
#PBS -m eba
#PBS -M cekees@gmail.com
cd $PBS_O_WORKDIR
mkdir $WORKDIR/bar.$PBS_JOBID
aprun -n 192  parun floating_bar_so.py -l 7 -v -p -O ../../inputTemplates/petsc.options.asm -C "refinement_level=2 parallel=True" -D $WORKDIR/bar.$PBS_JOBID
