-rans2p_ksp_type gmres -rans2p_pc_type asm   -rans2p_pc_asm_type   basic -rdls_ksp_gmres_modifiedgramschmidt -rdls_ksp_gmres_restart 200 -rans2p_sub_ksp_type preonly -rans2p_sub_pc_factor_mat_solver_package superlu
-ncls_ksp_type   gmres -ncls_pc_type   hypre -ncls_pc_hypre_type   boomeramg
-vof_ksp_type    gmres -vof_pc_type    hypre -vof_pc_hypre_type    boomeramg
-rdls_ksp_type   gmres -rdls_pc_type   hypre -rdls_pc_hypre_type   boomeramg -rdls_ksp_gmres_restart 200 -rdls_ksp_gmres_modifiedgramschmidt
-mcorr_ksp_type  cg     -mcorr_pc_type  hypre -mcorr_pc_hypre_type  boomeramg
-log_summary
