#!/bin/bash
#PBS -A ERDCV00898R40
#PBS -l walltime=008:00:00
#PBS -l select=8:ncpus=16:mpiprocs=16
#PBS -q standard
#PBS -N bar
#PBS -j oe
#PBS -l application=proteus
#PBS -V
#PBS -m eba
#PBS -M cekees@gmail.com
cd $PBS_O_WORKDIR
mpiexec_mpt -np ${BC_MPI_TASKS_ALLOC}  parun floating_bar_so.py -l 7 -v -O ../../inputTemplates/petsc.options.asm -C "refinement_level=2 parallel=True free_r=(0.0,0.0,0.0)" -D ${JOBDIR} -p
