
# Dump generated by HEXABLOCK at 2018/07/11 18:01:23

import hexablock

doc = hexablock.addDocument ('default')
rep001 = doc.countVertex ()
rep002 = doc.countVertex ()
rep003 = doc.countEdge ()
rep004 = doc.countQuad ()
rep005 = doc.countHexa ()
rep006 = doc.countVertex ()
law0 = doc.getLaw (0)
rep007 = doc.countVertex ()
rep008 = doc.countVertex ()
rep009 = doc.countEdge ()
rep010 = doc.countQuad ()
rep011 = doc.countHexa ()
rep012 = doc.countVertex ()
rep013 = doc.countVertex ()
